### ISSUE TITLE
Error when using cc0assetloader.

### ISSUE THREAD

**Issue by lemmih** [yuki-koyama/blender-cli-rendering#21]
Hi, script number 7 (as well as 8,9,10 and 12) fail with this error:

```
Blender 2.80 (sub 75)
Traceback (most recent call last):
  File "/home/david/coding/blender-cli-rendering/./07_texturing.py", line 66, in <module>
    focus_target = set_scene_objects()
  File "/home/david/coding/blender-cli-rendering/./07_texturing.py", line 14, in set_scene_objects
    loader.build_pbr_textured_nodes_from_name("Leather05")
  File "/home/david/coding/blender-cli-rendering/external/cc0assetsloader/__init__.py", line 144, in build_pbr_textured_nodes_from_name
    scale=scale)
  File "/home/david/coding/blender-cli-rendering/external/cc0assetsloader/__init__.py", line 124, in build_pbr_textured_nodes
    nodelayout.arrange_nodes(node_tree, use_current_layout_as_initial_guess=False)
AttributeError: module 'nodelayout' has no attribute 'arrange_nodes'
```

Do I need to install something to make it work?

**Comment by yuki-koyama** [comment]
Thank you for asking! 

This repository uses `git submodule` to include a dependency, cc0assetsloader <https://github.com/yuki-koyama/cc0assetsloader>, and so just using `git clone` or downloading as a zip file does not work. 

Also, cc0assetsloader uses `git lfs`, and so it is more complicated.

I guess the directory `./blender-cli-rendering/external/cc0assetsloader` is empty currently. Or, `./blender-cli-rendering/external/cc0assetsloader/nodelayout` is empty.

One straightforward solution is to
- install both `git` and `git-lfs`,
- clone this repository with `--recursive` option (<https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules>), and then
- run the scripts.

Another possible solution, which is probably easier, is to
- download cc0assetsloader directly from <https://github.com/yuki-koyama/cc0assetsloader/releases/download/0-1/cc0assetsloader.zip>,
- unzip it,
- replace `./blender-cli-rendering/external/cc0assetsloader` with the newly created directory, and then
- run the scripts.

Hope this helps. Sorry for the poor documentation!

**Comment by lemmih** [comment]
Ah, cloning with --recursive did the trick. I had tried 'git submodule init; git submodule update' but that didn't go deeply enough.
