### ISSUE TITLE
[Question] Transparent background

### ISSUE THREAD

**Issue by bsridatta** [yuki-koyama/blender-cli-rendering#32]
11_mesh_vizualization.py has the feature transparent background but the rendered image isn't transparent, even after changing the format to PNG to support alpha channel. When running the code with UI, I see that it does get the transparent background when I change the view of the rendering to View Layer -> combined. But the image being saved is using the Composite option instead of view layer. Is there anyway to enable saving the combined view layer? or any workaround. Thank you very much! 

![image](https://user-images.githubusercontent.com/17333185/100339343-08af1500-2fda-11eb-87fb-f760d4f643fc.png)

**Comment by yuki-koyama** [comment]
What Blender version are you using? If it is 2.9x, then the APIs may be changed since I wrote the script.

**Comment by bsridatta** [comment]
Thanks for the response. I am using 2.8 itself. Even the example 11_mesh_visualization.py has a gray background and not transparent. However in my case, though changing render film properties to transparent, the bg was black which is the default addition in the composite layer. Rendering without the composition nodes gave a true transparent image.
