### ISSUE TITLE
Support 2.93 LTS

### ISSUE THREAD

**Issue by yuki-koyama** [yuki-koyama/blender-cli-rendering#37]
The newest LTS (2.93) should be supported.

**Comment by vadimkantorov** [comment]
I've just downloaded blender release 2.93.2, fixed paths in `run.sh` and ran it, got `xcb_connection_has_error() returned true` and then hung / extremely slow running blender. Is it expected?

**Comment by vadimkantorov** [comment]
After a minute of wait, cube rendering worked :)

**Comment by vadimkantorov** [comment]
So I had to use `-noaudio`, on some headless systems Blender hangs trying to connect to pulse audio. I would recommend adding it to default running script if audio is not used...

**Comment by yuki-koyama** [comment]
Thank you very much for letting me know!! I will update the script very soon. 

#38
