### ISSUE TITLE
Considering python package

### ISSUE THREAD

**Issue by bsridatta** [yuki-koyama/blender-cli-rendering#44]
Hello @yuki-koyama, do you have any idea of converting the repo to a python library so folks can easily integrate it into their code base? Thank you!

**Comment by yuki-koyama** [comment]
Hi, thanks for the great suggestion.

Actually, I think this repo should have been designed as a python module (and a set of demo scripts). It is a good idea to convert the `util` directory into a python module that can be used as part of other Blender add-ons or as a library called from scripts within Blender.

Unfortunately, I don't have much time to work on this issue at the moment. Creating a pull request or fork repository would be welcome.

**Comment by bsridatta** [comment]
Thanks for the response @yuki-koyama. I shall see if I can get to it, not really sure. Thank you!
